f1 = open("triWriteFile.xt", "r")
print("Name of the file   ", f1.name)
print("closed r not  ", f1.closed)
print("Mode", f1.mode)
readAFile = f1.read()
print(readAFile)

print("---------------------------------------------------------")

f1 = open("triWritePlusFile.txt", "r+")
print("Name of the file   ", f1.name)
print("closed r not  ", f1.closed)
print("Mode", f1.mode)
f1.write("Welcome")
readAFile = f1.read()
print(readAFile)
